		<div class="portlet">
			<div class="portlet-heading">
			<form class="form" id="formulario_registro" method="POST" action="<?php echo $formAction ; ?>">
				<input type="hidden" id="latitud" name="latitud" value="0">
				<input type="hidden" id="longitud" name="longitud" value="0">
				<div class="row">
					<div class="portlet-heading dark">
						<div class="portlet-title"><h4>Usuarios Secundarios</h4></div>
						<div class="clearfix"></div>
					</div>
					<div class="col-lg-3 col-sm-6">
						<div class="form-group">
							<label for="id_usuario">Usuarios <small class="text-primary">(*)</small></label>
							<div class="input-group">
								<span class="input-group-addon"><i class="fa fa-check"></i></span>
								<select class="form-control" id="id_usuario" name="id_usuario">
									<option value="" selected="selected"> --- </option>
									<?php foreach($Usuarios as $key => $value){ ?>
										<option value="<?php echo $value["id"]; ?>"><?php echo $value["name"]; ?></option>
									<?php } ?>
								</select>
							</div>
						</div>
					</div>					
					<div class="col-lg-3 col-sm-6">
						<div class="form-group">
							<label for="nombre">Nombre <small class="text-primary">(*)</small></label>
							<div class="input-group">
								<span class="input-group-addon"><i class="fa fa-info"></i></span>
								<input type="text" id="nombre" name="nombre" class="form-control">
							</div>
						</div>
					</div>
					<div class="col-lg-3 col-sm-6">
						<div class="form-group">
							<label for="apellido">Apellido <small class="text-primary"></small></label>
							<div class="input-group">
								<span class="input-group-addon"><i class="fa fa-info"></i></span>
								<input type="text" id="apellido" name="apellido" class="form-control">
							</div>
						</div>
					</div>
					<div class="col-lg-3 col-sm-6">
						<div class="form-group">
							<label for="user">Usuario <small class="text-primary">(*)</small></label>
							<div class="input-group">
								<span class="input-group-addon"><i class="fa fa-info"></i></span>
								<input type="text" id="user" name="user" class="form-control">
							</div>
						</div>
					</div>
					<div class="col-lg-3 col-sm-6">
						<div class="form-group">
							<label for="pass">Password <small class="text-primary">(*)</small></label>
							<div class="input-group">
								<span class="input-group-addon"><i class="fa fa-info"></i></span>
								<input type="text" id="pass" name="pass" class="form-control">
							</div>
						</div>
					</div>
					<div class="col-lg-3 col-sm-6">
						<div class="form-group">
							<label for="status">Estatus <small class="text-primary">(*)</small></label>
							<div class="input-group">
								<span class="input-group-addon"><i class="fa fa-check"></i></span>
								<select class="form-control" id="status" name="status">
									<option value="" selected="selected"> --- </option>
									<option value="1">Activo</option>
									<option value="0">Inactivo</option>
								</select>
							</div>
						</div>
					</div>
					<div class="col-lg-3 col-sm-6">
						<div class="form-group">
							<label style="margin-bottom:2px !important;">&nbsp;</label>
							<div class="input-group">
								<button type="submit" class="btn btn-primary">Guardar</button>
							</div>
						</div>
					</div>
				</div>
			</form>
			<br />
			</div>
		</div>

<script type="text/javascript">noIndex=1;</script>



