	<form class="form" id="formulario_registro" enctype="multipart/form-data" method="POST" data-validate="parsley" action="<?php echo $formAction ; ?>">
		<section class="panel panel-default">
			<header class="panel-heading bg-light">
			  <ul class="nav nav-tabs nav-justified">
			    <li class="active"><a href="#tab1" data-toggle="tab">Datos Generales</a></li>
          
			  </ul>
			</header>
			<div class="panel-body">
			  <div class="tab-content">

			    <div class="tab-pane active" id="tab1">
            <div class="panel-body">
              <div class="form-group pull-in clearfix">
              <div class="col-sm-4">
                <label>Empresa (*)</label>
                <select class="form-control" id="id_empresa" name="id_empresa" data-required="true" <?php if($status != "") {echo "disabled";} ?>>
                  <option value="">---</option>
                  <?php 
                  if($Negocios != ""){
                    foreach ($Negocios as $key => $value) { 
                      echo "<option value='$value[id]' ".($id_negocio == $value["id"]?"selected":"").">$value[nombre]</option>";
                    }
                  } ?>
                </select>      
              </div>
                   <?php if(empty($archivo_disolucion) and $edit and $fecha_disolucion){?> 
                  <div class="col-sm-4">
                          <label>Documento Base Acta disolucion </label>
                          <select class="form-control" id="id_documento_disolucion" name="id_documento_disolucion">
                            <option value="">---</option>
                            <?php 
                            if($Documentos != ""){
                              foreach ($Documentos as $key => $value) { 
                                echo "<option value='$value[id]'>$value[nombre]</option>";  
                              }
                            } ?>
                          </select>      
                    </div>
                    <?php }?>
                   <?php if($edit and empty($archivo_disolucion) and $fecha_liquidacion){?> 
                  <div class="col-sm-4">
                          <label>Documento Base Acta liquidacion</label>
                          <select class="form-control" id="id_documento_liquidacion" name="id_documento_liquidacion">
                            <option value="">---</option>
                            <?php 
                            if($Documentos != ""){
                              foreach ($Documentos as $key => $value) { 
                                echo "<option value='$value[id]'>$value[nombre]</option>";  
                              }
                            } ?>
                          </select>      
                    </div>
                    <?php }?>
                   <div class="col-sm-4" >
                      <label>Nombre (Liquidador)</label>
                      <input type="text" id="liquidador" name="liquidador" class="form-control" data-required="true"> 
                   </div>
             

              <?php if(!empty($archivo_disolucion) and !empty($archivo_liquidacion)){?>
                    <div class="col-sm-4">
                          <label>Archivo</label>                     
                            <input type="file" class="filestyle" data-icon="false" data-classbutton="btn btn-default" data-classinput="form-control inline v-middle input-s" id="filestyle-0" style="position: fixed; left: -500px;" name="archivo" accept="application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/pdf">
                            <div class="bootstrap-filestyle" style="display: inline;">
                              <input type="text" class="form-control inline v-middle input-s" disabled="" id="archivo"> 
                              <label for="filestyle-0" class="btn btn-default"><span>Elige el archivo</span></label>
                            </div>                    
                    </div>   
              <?php }?>
                    <div class="col-sm-4">
                          <label>Costo de trámite (*)</label>
                          <input onkeypress="return isNumberKey(event);" class="form-control" id="costo_tramite" name="costo_tramite" data-required="true">
                    </div>
                    <div class="col-sm-4">
                          <label>Fecha de entrega (*)</label>
                          <input readonly class="form-control" id="fecha_entrega" name="fecha_entrega" data-required="true">
                    </div>
                    <?php if($status != "") {?>
                      <?php for ($i = $status; $i <= ($status+1); $i++) { ?>
                      <div class="col-sm-4">
                            <label><?php echo $status==$i?"Fin $Status[$i]":"Inicio $Status[$i]";?></label>
                            <input class="form-control" id="fecha<?php echo $i;?>" name='<?php echo $status==$i?"fin_$Status_Fechas[$i]":"inicio_$Status_Fechas[$i]";?>' readonly >      
                      </div>
                      <?php } ?>
                    <?php }?>
               
               <!-- <textarea name="contenido" id="contenido"cols="" rows="" data-required="true"></textarea> -->
               
              <!--   -->


              
              <div class="col-sm-4">
              <?php if(isset($archivo_disolucion) and !empty($archivo_disolucion)){?>
                  <a target="_blank" href="tmp/tramites/<?php echo $archivo_disolucion?>"> Acta disolucion <img src="images/paper.png"></a>
              <?php }?>


              </div>
              <div class="col-sm-4">
              <?php if(isset($archivo_liquidacion) and !empty($archivo_liquidacion)){?>
                  <a target="_blank" href="tmp/tramites/<?php echo $archivo_liquidacion?>"> Acta liquidacion <img src="images/paper.png"></a>
              <?php }?>


              </div>


              <?php if($status != "") {?>
              <div class="col-sm-4">
                    <label>Cometario <?php echo $Status[$status];?></label>
                    <input class="form-control" id="comentario_<?php echo $Status_Fechas[$status];?>" name="comentario_<?php echo $Status_Fechas[$status];?>">     
              </div>
              <?php }?>

               

              <?php if($status != "") {?>

              <div class="col-sm-8"></div>

              <div class="col-sm-4">
                    <label>Estatus (*)</label>
                    <select class="form-control" id="status" name="status" data-required="true">
                     <option value="" > --- </option>
                     <?php for ($i = $status; $i <= ($status+1); $i++) { ?>
                       <option value="<?php echo $i ?>" > <?php echo $Status[$i];?> </option>
                    <?php } ?>
                    </select>      
              </div>
              <?php }?>





                 
              </div>
            
             <!-- <div class="clear" style="padding:15px;"></div>-->
             

              
            </div>
            <footer class="panel-footer text-right bg-light lter">
              <button type="submit" class="btn btn-success btn-s-xs">Guardar</button>
            </footer>
			    </div>
         
			  </div>
			</div>
		</section>
	</form>
	<div style="clear: both;">&nbsp;</div>
	<div style="clear: both;">&nbsp;</div>
	<div style="clear: both;">&nbsp;</div>
<!--<script type="text/javascript">$('#cke_contenido').css('height','400');</script>-->

