  <style type="text/css" media="screen">
  	.delete_usuarios{z-index: 999}	
  </style>
  <section class="panel panel-default">
	<header class="panel-heading">
		<div align="right">
			<a href="tramites/new" class="btn btn-sm btn-icon btn-success"><i class="fa fa-plus"></i></a>
		</div>
	</header>
    <div class="table-responsive">
      <table class="table table-striped m-b-none" data-ride="datatables" id="grid_listado">
        <thead>
          <tr>
            <th width="5%">No</th>             
            <th width="15%">Empresa</th>
            <th width="15%">Liquidador</th>
            <th width="10%">Fecha Creación</th>           
            <th width="10%">Estatus</th>
            <th width="10%">&nbsp;</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
  </section>
<?php echo $msjResponse; ?>