<section class="hbox stretch">
            <section>
              <section class="vbox">
                <section class="scrollable padder" style="padding-bottom: 50px;";>              
                  


<section class="row m-b-md">
                    <div class="col-sm-6">
                      <h3 class="m-b-xs text-black">Panel Administrador</h3>
                      
                    </div>
                   
                  </section>
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="panel b-a">
                        <div class="row m-n">
                          <div class="col-md-4 b-b b-r">
                            <a href="#" class="block padder-v hover">
                              <span class="i-s i-s-2x pull-left m-r-sm">
                                <i class="i i-hexagon2 i-s-base text-danger hover-rotate"></i>
                                <i class="i i-plus2 i-1x text-white"></i>
                              </span>
                              <span class="clear">
                                <span class="h3 block m-t-xs text-danger"><?php echo $NumTramites ?></span>
                                <small class="text-muted text-u-c">Tramites </small>
                              </span>
                            </a>
                          </div>
                          <div class="col-md-4 b-b">
                            <a href="#" class="block padder-v hover">
                              <span class="i-s i-s-2x pull-left m-r-sm">
                                <i class="i i-hexagon2 i-s-base text-success-lt hover-rotate"></i>
                                <i class="i i-users2 i-sm text-white"></i>
                              </span>
                              <span class="clear">
                                <span class="h3 block m-t-xs text-success"><?php echo $NumClientes ?></span>
                                <small class="text-muted text-u-c">Clientes</small>
                              </span>
                            </a>
                          </div>
                          
                          <div class="col-md-4 b-b">
                            <a href="#" class="block padder-v hover">
                              <span class="i-s i-s-2x pull-left m-r-sm">
                                <i class="i i-hexagon2 i-s-base text-primary hover-rotate"></i>
                                <i class="i i-bookmark i-sm text-white"></i>
                              </span>
                              <span class="clear">
                                <span class="h3 block m-t-xs text-primary"><?php echo $NumEmpresas ?></span>
                                <small class="text-muted text-u-c">Empresas</small>
                              </span>
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                    
                   
                   
                  </div>           
                  <div class="row bg-light dk m-b">
                    <div class="col-md-6 ">
                      <p></p>
                      <section class="panel panel-default">
                        <header class="panel-heading font-bold">Estatus de Tramites</header> 
                        <div class="panel-body">
                          <div id="estatus_tramites" style="height: 240px; padding: 0px; position: relative;">
                           
                          </div>
                        </div> 
                      </section>
                    </div>
                    <div class="col-md-6">
                       <p></p>
                      <section class="panel panel-default">
                        <header class="panel-heading font-bold">Tramites  x Mes</header> 
                        <div class="panel-body">
                          <div id="tramites_mes" style="height: 240px; padding: 0px; position: relative;">
                           
                          </div>
                        </div> 
                      </section>

                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-12"> 
                      <section class="panel panel-default"> 
                        <header class="panel-heading"> 
                          <div class="input-group text-sm"> 
                            <input type="text" class="input-sm form-control" placeholder="Buscar"> 
                            <div class="input-group-btn"> 
                              <button type="button" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown">Buscar <span class="caret"></span></button> 
                              
                            </div> 
                          </div> 
                        </header> 
                        <ul class="list-group alt"> 
                          <li class="list-group-item"> 
                            <div class="media"> 
                              <span class="pull-left thumb-sm"><img src="images/processing-file.png"  class="img-circle"></span> 
                              <div class="pull-right text-success m-t-sm"> <i class="fa fa-circle"> Notaria</i></div>  
                              <div class="media-body"> 
                                <div><a href="#"><small class="text-muted"> Tramite No. 001</a></div><b>Costo $</b> 1800 | <b>Pagos a la fecha:</b> $000 | <b> Restante:</b>  $000 </small> 
                              </div> 
                            </div> 
                          </li> 


                           <li class="list-group-item"> 
                            <div class="media"> 
                              <span class="pull-left thumb-sm"><img src="images/processing-file.png"  class="img-circle"></span> 
                              <div class="pull-right text-danger m-t-sm"> <i class="fa fa-circle"> SAT</i></div>  
                              <div class="media-body"> 
                                <div><a href="#"><small class="text-muted"> Tramite No. 002</a></div><b>Costo $</b> 1800 | <b>Pagos a la fecha:</b> $000 | <b> Restante:</b>  $000 </small> 
                              </div> 
                            </div> 
                          </li> 

                    
                      </ul> 
                      </section>                        
                    </div>
                  </div>
                 
                </section>
                 
              </section>
              
            </section>
            
          </section>
          <script type="text/javascript">
          $( document ).ready(function() {
            var da = [
                      {
                        label: "Notaria",
                        data: 40
                      },    
                      {
                        label: "RPC",
                        data: 10
                      },
                      {
                        label: "SAT",
                        data: 20
                      },
                      {
                        label: "Concluido",
                        data: 12
                      },
                     
                    ], 
                da1 = [],
                series = Math.floor(Math.random() * 4) + 3;

                for (var i = 0; i < series; i++) {
                  da1[i] = {
                    label: "Series" + (i + 1),
                    data: Math.floor(Math.random() * 100) + 1
                  }
                }

                 $("#estatus_tramites").length && $.plot($("#estatus_tramites"), da, {
                    series: {
                      pie: {
                        combine: {
                              color: "#999",
                              threshold: 0.05
                            },
                        show: true
                      }
                    },    
                    colors: ["#65b5c2","#4da7c1","#3993bb","#2e7bad","#23649e"],
                    legend: {
                      show: false
                    },
                    grid: {
                        hoverable: true,
                        clickable: false
                    },
                    tooltip: true,
                    tooltipOpts: {
                      content: "%s: %p.0%"
                    }
                  });


                //////////////////////////////////////////////////////
                  var datos = [
                      {
                        label: "Enero",
                        data: 40
                      },    
                      {
                        label: "Febrero",
                        data: 10
                      },
                      {
                        label: "Marzo",
                        data: 20
                      },
                      {
                        label: "Abril",
                        data: 12
                      },
                     
                    ], 
                da2 = [],
                series2 = Math.floor(Math.random() * 4) + 3;
                 for (var i = 0; i < series2; i++) {
                    da2[i] = {
                      label: "Series" + (i + 1),
                      data: Math.floor(Math.random() * 100) + 1
                    }
                  }

                   $("#tramites_mes").length && $.plot($("#tramites_mes"), datos, {
                        series: {
                          pie: {
                            innerRadius: 0.4,
                            show: true,
                            stroke: {
                              width: 0
                            },
                            label: {
                              show: true,
                              threshold: 0.05
                            },

                          }
                        },
                        colors: ["#65b5c2","#4da7c1","#3993bb","#2e7bad","#23649e"],
                        grid: {
                            hoverable: true,
                            clickable: false
                        },
                        tooltip: true,
                        tooltipOpts: {
                          content: "%s: %p.0%"
                        }
                      });
               
                

          });

 

          </script>
