<section class="hbox stretch">
  <section class="vbox">
    <section class="scrollable padder">
    <div class="doc-buttons"> 
    <a href="#" class="btn btn-s-md btn-primary" onclick="JsActivarCamara(); return false ">Leer QR</a> 
    <a href="#" class="btn btn-s-md btn-success">Correo Electrónico </a> 
    <a href="#" class="btn btn-s-md btn-info">Registro</a> 
    <!--<a href="#" class="btn btn-s-md btn-warning">Warning</a> 
    <a href="#" class="btn btn-s-md btn-danger">Danger</a> 
    <a href="#" class="btn btn-s-md btn-dark">Dark</a>
     <a href="#" class="btn btn-s-md btn-default disabled">Disabled</a> -->
     </div>

     <div class="form-group pull-in clearfix">
         <div class="col-sm-6">
               <!-- qr-->
               <div id="area_qr" > 
               <div id="result"></div> 
                     <!-- <div class="row">
                          <div class="col-md-12">
                             <h3>Lector de codigo</h3>
                             <div id="reader" style="width:300px;height:250px">
                             </div>
                             <h6>...</h6>
                             <span id="read" class="center"></span>
                             <br>


                         </div>
                     </div>-->                
                     
               </div>
               <div id="outdiv"><video id="v" autoplay="" src=""></video></div>
               <canvas id="qr-canvas" width="800" height="600"></canvas>

              <!-- qr--> 

         </div>
         <div class="col-sm-6">
            <div id="resultado_qr"></div>
         </div>

     </div>  


    </section>    
  </section>  
</section>
<script type="text/javascript">
  
$( document ).ready(function() {
//JsActivarCamara(); 
load();
  
});


function JsActivarCamara(){    
    
   // $('#area_qr').show();
      $('#reader').html5_qrcode(function (data) {
         $('#resultado_qr').html('<div aling="center"><div><img src="images/loading.gif"></div> <div><h3>Cargando...</h3></div> </div>');
        
     $.ajax({ 
      type: "GET", 
      crossDomain : true,
            url: "home/qr/"+data ,
            dataType:'html',
            success: function(data) {  
                $('#resultado_qr').html(data);
                setTimeout(function(){ $('#resultado_qr').html('') }, 10000);
                          
            }
        }); 
         /*fghfgh*/  
      

   });


  }

</script>