	<form class="form" id="formulario_registro" enctype="multipart/form-data" method="POST" data-validate="parsley" action="<?php echo $formAction ; ?>">
		<section class="panel panel-default">
			<header class="panel-heading bg-light">
			  <ul class="nav nav-tabs nav-justified">
			    <li class="active"><a href="#tab1" data-toggle="tab">Datos Generales</a></li>
          
			  </ul>
			</header>
			<div class="panel-body">
			  <div class="tab-content">

			    <div class="tab-pane active" id="tab1">
            <div class="panel-body">
              <div class="form-group pull-in clearfix">

                <div class="col-sm-5">
                  <label>Nombre</label>
                  <input type="text" id="nombre" name="nombre" class="form-control" data-required="true">  
                  
                   
                </div>
                
                <div class="col-sm-5">
                      <label>Estatus (*)</label>
                      <select class="form-control" id="status" name="status" data-required="true">
                        
                        <option value="1">Activo</option>
                        <option value="0">Inactivo</option>
                      </select>      
                </div>

                <div style=" margin-bottom:15px; clear:both; "></div>
                <textarea name="contenido" id="contenido"cols="" rows="" data-required="true"></textarea>
               
               <!--  <div class="col-sm-8">
                      <label>Imagen</label>                     
                        <input type="file" class="filestyle" data-icon="false" data-classbutton="btn btn-default" data-classinput="form-control inline v-middle input-s" id="filestyle-0" style="position: fixed; left: -500px;" name="img" accept="image/*">
                        <div class="bootstrap-filestyle" style="display: inline;">
                          <input type="text" class="form-control inline v-middle input-s" disabled=""> 
                          <label for="filestyle-0" class="btn btn-default"><span>Elige una imagen</span></label>
                        </div>                    
                </div> -->





                 
              </div>
            
             <!-- <div class="clear" style="padding:15px;"></div>-->
             

              
            </div>
            <footer class="panel-footer text-right bg-light lter">
              <button type="submit" class="btn btn-success btn-s-xs">Guardar</button>
            </footer>
			    </div>
         
			  </div>
			</div>
		</section>
	</form>
	<div style="clear: both;">&nbsp;</div>
	<div style="clear: both;">&nbsp;</div>
	<div style="clear: both;">&nbsp;</div>
<!--<script type="text/javascript">$('#cke_contenido').css('height','400');</script>-->

