	<form class="form" id="formulario_registro" method="POST" data-validate="parsley" action="<?php echo $formAction ; ?>">
		<section class="panel panel-default">
			<header class="panel-heading bg-light">
			  <ul class="nav nav-tabs nav-justified">
			    <li class="active"><a href="#tab1" data-toggle="tab">Datos Generales</a></li>
			    <?php if ($_SESSION['tipo']=='Administrador') {?>
			    <li><a href="#tab2" data-toggle="tab">Permisos</a></li>
			    <?php }?>
			  </ul>
			</header>
			<div class="panel-body">
			  <div class="tab-content">
			    <div class="tab-pane active" id="tab1">
                      <div class="panel-body">
                        <div class="form-group">
                          	<label>Tipo Usuario (*)</label>
                          	<?php 
	                          	if ($_SESSION['tipo']=='Administrador') {
	                          		$opciones='
	                          			<option value="" selected="selected"> --- </option>
	                          			<option value="Administrador">Administrador</option>
	                          			<option value="Negocio">Negocio</option>';	                          		
	                          	} 

	                          	if ($_SESSION['tipo']=='Negocio') {
	                          		$opciones='
	                          			<option value="" selected="selected"> --- </option>
	                          			<option value="Negocio">Administrador</option>	                          			
	                          			<option value="Vendedor">Vendedor</option>
	                          			<option value="Tablet">Tablet</option>

	                          			';	  
	                          	} 

                          	?>
							<select class="form-control" id="tipo" name="tipo"  onchange="tipoUsuario();" data-required="true">
								<?php echo $opciones;?>
							</select>                                               
                        </div>

                       <?php   if ($_SESSION['tipo']=='Negocio') {?>
                         <div class="form-group" id="select_sucursales" style="display: none;">
                          	<label>Sucursal(*)</label>                          	
							<select class="form-control" id="id_sucursal" name="id_sucursal"  data-required="true">
								<option value="" selected="selected"> --- </option>
								<?php if(!empty($Sucursales)){ for ($i=0; $i <count($Sucursales) ; $i++) {?> 
									<option value="<?php echo $Sucursales[$i]['id']; ?>" > <?php echo $Sucursales[$i]['nombre']; ?> </option>
								<?php  }}  	?>
								Sucursales
							</select>                                               
                        </div>
 						<?php }?>

                        <div class="form-group">
                          <label>Nombre (*)</label>
                          <input type="text" id="nombre" name="nombre" class="form-control" data-required="true">
                        </div>
                        <div class="form-group">
                          <label>Apellido</label>
                          <input type="text" id="apellido" name="apellido" class="form-control">
                        </div>
						<div class="form-group">
                          <label>Email (*)</label>
                          <input type="text" id="email" name="email" class="form-control" data-type="email" data-required="true">
                        </div>
                        <div class="form-group">
                          <label>Usuario (*)</label>
                          <input type="text" id="user" name="user" class="form-control" data-required="true">
                        </div>
                        <div class="form-group pull-in clearfix">
                          <div class="col-sm-6">
                            <label>Password (*)</label>
                            <input type="password" id="pass" name="pass" class="form-control" data-required="true">   
                          </div>
                          <div class="col-sm-6">
                            <label>Confirmar password (*)</label>
                            <input type="password" id="pass2" name="pass2" class="form-control" data-equalto="#pass" data-required="true">      
                          </div>   
                        </div>
                        <div class="form-group">
                          	<label>Estatus (*)</label>
							<select class="form-control" id="status" name="status" data-required="true">
								<option value="" selected="selected"> --- </option>
								<option value="1">Activo</option>
								<option value="0">Inactivo</option>
							</select>                                               
                        </div>
                      </div>
                      <footer class="panel-footer text-right bg-light lter">
                        <button type="submit" class="btn btn-success btn-s-xs">Guardar</button>
                      </footer>
			    </div>
			     <?php if ($_SESSION['tipo']=='Administrador') {?>
			    <div class="tab-pane" id="tab2">
					<div class="form-group pull-in clearfix">
					<?php foreach($Permisos as $key => $value){ ?>
						<div class="col-sm-12"><center><div class="titulo_modulo_conteiner">Módulo <?php echo substr($key, 4);?></div></center></div>
						<div class="col-sm-6">
							<label class="i-checks">
								<input type="checkbox" id="permiso_<?php echo $key ; ?>" name="permiso_<?php echo $key ; ?>" value="1"><i></i> <?php echo $key; ?>
							</label>
						</div>
						<?php foreach($Permisos[$key] as $_key => $_value){ ?>
						<div class="col-sm-6">
								<label class="i-checks">
								<input type="checkbox" id="permiso_<?php echo $_value ; ?>" name="permiso_<?php echo $_value ; ?>" value="1"><i></i> <?php echo $_value; ?>
							</label>
						</div>
						<?php } ?>
						<div style="clear: both;">&nbsp;</div>
						<hr class="">
					<?php } ?>
					</div>
					<footer class="panel-footer text-right bg-light lter">
                        <button type="submit" class="btn btn-success btn-s-xs">Guardar</button>
                    </footer>
			    </div>

			    <?php  } 	?>
			  </div>
			</div>
		</section>
	</form>
	<div style="clear: both;">&nbsp;</div>
	<div style="clear: both;">&nbsp;</div>
	<div style="clear: both;">&nbsp;</div>
<script type="text/javascript">actionForm=1;</script>

